// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package schema

type Mutation struct {
}

type Query struct {
}

type UserInput struct {
	Username    string `json:"username"`
	Mailaddress string `json:"mailaddress"`
	Password    string `json:"password"`
}
