// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package schema

import (
	"time"
)

type Comment struct {
	ID        int       `json:"id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	User      *User     `json:"user"`
	Post      *Post     `json:"post"`
}

type Like struct {
	ID        int       `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	User      *User     `json:"user"`
	Post      *Post     `json:"post"`
}

type Mutation struct {
}

type Post struct {
	ID        int        `json:"id"`
	Content   string     `json:"content"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	User      *User      `json:"user"`
	Comments  []*Comment `json:"comments"`
	Likes     []*Like    `json:"likes"`
}

type Query struct {
}

type User struct {
	ID          int        `json:"id"`
	Username    string     `json:"username"`
	Mailaddress string     `json:"mailaddress"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	Posts       []*Post    `json:"posts"`
	Comments    []*Comment `json:"comments"`
	Likes       []*Like    `json:"likes"`
}
