/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UserShowImport } from './routes/user/show'
import { Route as UserNewImport } from './routes/user/new'
import { Route as PostsNewImport } from './routes/posts/new'
import { Route as PostsPostIdImport } from './routes/posts/$postId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserShowRoute = UserShowImport.update({
  path: '/user/show',
  getParentRoute: () => rootRoute,
} as any)

const UserNewRoute = UserNewImport.update({
  path: '/user/new',
  getParentRoute: () => rootRoute,
} as any)

const PostsNewRoute = PostsNewImport.update({
  path: '/posts/new',
  getParentRoute: () => rootRoute,
} as any)

const PostsPostIdRoute = PostsPostIdImport.update({
  path: '/posts/$postId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdImport
      parentRoute: typeof rootRoute
    }
    '/posts/new': {
      id: '/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof PostsNewImport
      parentRoute: typeof rootRoute
    }
    '/user/new': {
      id: '/user/new'
      path: '/user/new'
      fullPath: '/user/new'
      preLoaderRoute: typeof UserNewImport
      parentRoute: typeof rootRoute
    }
    '/user/show': {
      id: '/user/show'
      path: '/user/show'
      fullPath: '/user/show'
      preLoaderRoute: typeof UserShowImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  PostsPostIdRoute,
  PostsNewRoute,
  UserNewRoute,
  UserShowRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/posts/$postId",
        "/posts/new",
        "/user/new",
        "/user/show"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/posts/$postId": {
      "filePath": "posts/$postId.tsx"
    },
    "/posts/new": {
      "filePath": "posts/new.tsx"
    },
    "/user/new": {
      "filePath": "user/new.tsx"
    },
    "/user/show": {
      "filePath": "user/show.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
